[workspace]
resolver = "3"
members = [
    "crates/*",
]

[workspace.package]
edition = "2024"
version = "0.1.13"
authors = ["suji contributors"]

[workspace.dependencies]
ariadne = "0.5.1"
chumsky = "0.10.1"
indexmap = "2.11.0"
once_cell = "1.21.3"
regex = "1.11.2"
rustyline = "17.0.1"
serde_json = "1.0"
serde_yaml2 = "0.1"
thiserror = "2.0.16"
toml = "0.8"
yaml-rust2 = "0.10.3"
rand = "0.8"
rust_decimal = "1.36"
