[package]
name = "nnlang"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.5.1"
chumsky = "0.10.1"
indexmap = "2.11.0"
logos = "0.15.1"
once_cell = "1.21.3"
regex = "1.11.2"
rustyline = "17.0.1"
thiserror = "2.0.16"
