[package]
name = "suji-runtime"
version = "0.1.21"
edition = "2024"

[dependencies]
suji-ast = { path = "../suji-ast" }
suji-values = { path = "../suji-values" }
indexmap = { workspace = true }
once_cell = { workspace = true }

