[package]
name = "suji-lexer"
version = "0.1.17"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
regex = { workspace = true }
thiserror = { workspace = true }
suji-ast = { path = "../suji-ast" }
